services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: kiosk
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pharmacy
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
